language: node_js
node_js:
  - 8

matrix:
  include:
    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - src/node_modules
    - electron

script: npm run package
